name: fundamental_submission
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <=3.3.8'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  http: ^0.13.5
  cached_network_image: ^3.2.3
  google_fonts: ^2.0.0  
  flutter_rating_bar: ^4.0.1
  expandable_text: ^2.3.0
  dropdown_button2: ^2.0.0
  connectivity_plus: ^3.0.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

